### PR TITLE
fix: make `iap_config` `log_config` optional and set `enable_cdn` default value to `false`

### PR DESCRIPTION
**Pull request by ushuz**
Make these configs truly optional to avoid Terraform complaining:

- For `iap_config` `log_config`:

```
Step #1 - "terraform-plan": Error: Invalid value for input variable
Step #1 - "terraform-plan": 
Step #1 - "terraform-plan":   on cloudrun.tf line 193, in module "lb":
Step #1 - "terraform-plan":  193:   backends = {
Step #1 - "terraform-plan":  194:     default = {
Step #1 - "terraform-plan":  195:       groups = [
Step #1 - "terraform-plan":  196:         {
Step #1 - "terraform-plan":  197:           group = google_compute_region_network_endpoint_group.neg.id
Step #1 - "terraform-plan":  198:         }
Step #1 - "terraform-plan":  199:       ]
Step #1 - "terraform-plan":  200:     }
Step #1 - "terraform-plan":  201:   }
Step #1 - "terraform-plan": 
Step #1 - "terraform-plan": The given value is not suitable for module.lb.var.backends declared at .terraform/modules/lb/modules/serverless_negs/variables.tf:58,1-20: "terraform-plan": element "default": attributes "iap_config" and "log_config" are required.
```

- For `enable_cdn`:

```
Step #1 - "terraform-plan": Error: Null condition
Step #1 - "terraform-plan": 
Step #1 - "terraform-plan":   on .terraform/modules/lb/modules/serverless_negs/main.tf line 238, in resource "google_compute_backend_service" "default":
Step #1 - "terraform-plan":  238:     for_each = each.value.enable_cdn ? [1] : []
Step #1 - "terraform-plan":     ├────────────────
Step #1 - "terraform-plan":     │ each.value.enable_cdn is null
Step #1 - "terraform-plan": 
Step #1 - "terraform-plan": The condition value is null. Conditions must either be true or false.
```

### CODE REVIEW

**Comment by imrannayer** [comment]
@ushuz thx for the PR. Can you plz follow [contribution guide](https://github.com/terraform-google-modules/terraform-google-lb-http/blob/master/CONTRIBUTING.md) to update template and generate terraform?

Thanks

**Comment by ushuz** [comment]
@imrannayer - Updated, thanks.

**Comment by imrannayer** [comment]
@ushuz test are failing on image. Can you plz update all image family with the ones available. 

```
gcloud compute images list
```


```
  with module.example.module.mig2_template.google_compute_instance_template.tpl,
  on .terraform/modules/example.mig2_template/modules/instance_template/main.tf line 62, in resource "google_compute_instance_template" "tpl":
  62: resource "google_compute_instance_template" "tpl" {


Error: Error resolving image name 'centos-cloud/centos-7': Could not find image or family centos-cloud/centos-7
```

**Comment by ushuz** [comment]
@imrannayer - Update the branch

**Comment by imrannayer** [comment]
> @imrannayer - Update the branch

@ushuz can u update all the example folder pointing to centos7. Change them to centos-stream-9

**Comment by ushuz** [comment]
@imrannayer - Sorry, I don't know how to do that. Can you update the branch directly? It's editable by the maintainers.

image

**Pull request closed without merging**
