### PR TITLE
add protocol to backend

### LINKED ISSUE #201: Missing HTTPS protocol for backend service
Hi,

I was wondering if there is a specific reason to not include `protocol` param in the backend service.

I can see it's supported here: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_backend_service#protocol

but currently missing from:
https://github.com/terraform-google-modules/terraform-google-lb-http/blob/master/modules/serverless_negs/main.tf#L157

And I believe it's missing from:
https://github.com/terraform-google-modules/terraform-google-lb-http/blob/master/modules/serverless_negs/main.tf#L174

 The scenario is the following, create HTTPS only LB for CloudRun.
 
 Greetings

### PR DESCRIPTION
**Pull request by anovis**
protocol not getting passed for serverless NEG since only HTTP is supported. However, for internet NEG, this can be configured to be HTTPS or HTTP. I would like to be able to set it, since everything else works in this module for internet NEG. Currently I use this module and then manually have the change in the ui the internet NEG protocol from http to https.  
closes #201 

https://cloud.google.com/load-balancing/docs/negs#internet-neg
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_backend_service

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_generate_modules
 The modules need to be regenerated. Please run `make_build`. 
 ```bash 
Checking submodule's files generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/serverless_negs/main.tf /tmp/tmp.FrsURigL1t/workspace/modules/serverless_negs/main.tf
179d178
<   protocol                        = lookup(each.value, "protocol", null)
Error: submodule's files generation has not been run, please run the
'make build' command and commit changes
 ``` 
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
Running terraform validate
terraform_validate . 
Success!
 The configuration is valid.
terraform_validate ./examples/cloudrun 
Success!
 The configuration is valid.
terraform_validate ./examples/https-gke 
╷
│
 
Error: 
Invalid Configuration for Read-Only Attribute
│
 
│
 
  with tls_self_signed_cert.example,
│
 
  on tls.tf line 23, in resource "tls_self_signed_cert" "example":
│
 
  23:   key_algorithm   = 
tls_private_key.example.algorithm
│
 
│
 
Cannot set value for this attribute as the provider has marked it as
│
 
read-only. Remove the configuration line setting the value.
│
 
│
 
Refer to the provider documentation or contact the provider developers for
│
 
additional information about configurable and read-only attributes that are
│
 
supported.
╵
terraform_validate ./examples/https-gke/gke-node-port 
Success!
 The configuration is valid.
terraform_validate ./examples/https-redirect 
╷
│
 
Error: 
Invalid Configuration for Read-Only Attribute
│
 
│
 
  with tls_self_signed_cert.example,
│
 
  on tls.tf line 23, in resource "tls_self_signed_cert" "example":
│
 
  23:   key_algorithm   = 
tls_private_key.example.algorithm
│
 
│
 
Cannot set value for this attribute as the provider has marked it as
│
 
read-only. Remove the configuration line setting the value.
│
 
│
 
Refer to the provider documentation or contact the provider developers for
│
 
additional information about configurable and read-only attributes that are
│
 
supported.
╵
terraform_validate ./examples/mig-nat-http-lb 
Success!
 The configuration is valid.
terraform_validate ./examples/multi-backend-multi-mig-bucket-https-lb 
╷
│
 
Error: 
Invalid Configuration for Read-Only Attribute
│
 
│
 
  with tls_self_signed_cert.example,
│
 
  on tls.tf line 23, in resource "tls_self_signed_cert" "example":
│
 
  23:   key_algorithm   = 
tls_private_key.example.algorithm
│
 
│
 
Cannot set value for this attribute as the provider has marked it as
│
 
read-only. Remove the configuration line setting the value.
│
 
│
 
Refer to the provider documentation or contact the provider developers for
│
 
additional information about configurable and read-only attributes that are
│
 
supported.
╵
terraform_validate ./examples/multi-mig-http-lb 
Success!
 The configuration is valid.
terraform_validate ./examples/multiple-certs 
╷
│
 
Error: 
Invalid Configuration for Read-Only Attribute
│
 
│
 
  with tls_self_signed_cert.example,
│
 
  on tls.tf line 25, in resource "tls_self_signed_cert" "example":
│
 
  25:   key_algorithm   = 
tls_private_key.example[count.index].algorithm
│
 
│
 
Cannot set value for this attribute as the provider has marked it as
│
 
read-only. Remove the configuration line setting the value.
│
 
│
 
Refer to the provider documentation or contact the provider developers for
│
 
additional information about configurable and read-only attributes that are
│
 
supported.
╵
terraform_validate ./examples/shared-vpc 
Success!
 The configuration is valid.
terraform_validate ./modules/dynamic_backends 
Success!
 The configuration is valid.
terraform_validate ./modules/serverless_negs 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/cloudrun 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/https-redirect 
╷
│
 
Error: 
Invalid Configuration for Read-Only Attribute
│
 
│
 
  with module.example.tls_self_signed_cert.example,
│
 
  on ../../../examples/https-redirect/tls.tf line 23, in resource "tls_self_signed_cert" "example":
│
 
  23:   key_algorithm   = 
tls_private_key.example.algorithm
│
 
│
 
Cannot set value for this attribute as the provider has marked it as
│
 
read-only. Remove the configuration line setting the value.
│
 
│
 
Refer to the provider documentation or contact the provider developers for
│
 
additional information about configurable and read-only attributes that are
│
 
supported.
╵
terraform_validate ./test/fixtures/mig_nat 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/multi_certs 
╷
│
 
Error: 
Invalid Configuration for Read-Only Attribute
│
 
│
 
  with module.example.tls_self_signed_cert.example,
│
 
  on ../../../examples/multiple-certs/tls.tf line 25, in resource "tls_self_signed_cert" "example":
│
 
  25:   key_algorithm   = 
tls_private_key.example[count.index].algorithm
│
 
│
 
Cannot set value for this attribute as the provider has marked it as
│
 
read-only. Remove the configuration line setting the value.
│
 
│
 
Refer to the provider documentation or contact the provider developers for
│
 
additional information about configurable and read-only attributes that are
│
 
supported.
╵
terraform_validate ./test/fixtures/multi_mig 
Success!
 The configuration is valid.
terraform_validate ./test/setup 
Success!
 The configuration is valid.
 ```

**Review by bharathkkb — COMMENTED** [review]
Thanks for the PR! Could you fix the formatting in https://github.com/terraform-google-modules/terraform-google-lb-http/pull/259#issuecomment-1198432219

**Comment by anovis** [comment]
@bharathkkb  i may need help getting it to format. i fix one by running terraform fmt, but then it fails saying to do terraform make build, which then causes the format to fail. any advice?

**Comment by bharathkkb** [comment]
@anovis I think moving it to separate line may do the trick

**Comment by anovis** [comment]
:(

**Comment by anovis** [comment]
closing for #285.

**Pull request closed without merging**
