### PR TITLE
feat!: add support for https only procotol in NEG backend service

### PR DESCRIPTION
**Pull request by gangsta**
Hi @morgante .
here is an example of the setup we want to accomplish.

The current setup is by default creating HTTP only or HTTP and HTTPS protocols for NEG. But in my case, we need only HTTPS only. 

Case with Google Cloud - Cloud Run with external CDN like Cloudflare.

config example is going to be
```
module "neg_external" {
  source               = "GoogleCloudPlatform/lb-http/google//modules/serverless_negs"
  version              = "~> 5.1"
  name                 = "neg-external"
  project              = var.project_id
  ssl                  = true
  ssl_certificates     = ["projects/someproject-here/global/sslCertificates/wildcard-certificate"]
  use_ssl_certificates = true
  http_forward         = false
  create_address       = false
  address              = "someiphere"

  backends = {
    default = {
      description                     = null
      protocol                        = "HTTPS"
      port                            = 443
      port_name                       = "https"
      timeout_sec                     = 300
      connection_draining_timeout_sec = 60
      enable_cdn                      = false
      security_policy                 = google_compute_security_policy.allow_some_policy.self_link
      session_affinity                = null
      affinity_cookie_ttl_sec         = null
      custom_request_headers          = null
      custom_response_headers         = null

      log_config = {
        enable      = true
        sample_rate = null
      }

      groups = [
        {
          group                        = google_compute_region_network_endpoint_group.some_neg.id
          balancing_mode               = null
          capacity_scaler              = null
          description                  = null
          max_connections              = null
          max_connections_per_instance = null
          max_connections_per_endpoint = null
          max_rate                     = null
          max_rate_per_instance        = null
          max_rate_per_endpoint        = null
          max_utilization              = null
        }
      ]
      iap_config = {
        enable               = false
        oauth2_client_id     = ""
        oauth2_client_secret = ""
      }
    }
  }
}
```

Some History of PR 
The old PR: https://github.com/terraform-google-modules/terraform-google-lb-http/pull/205
Issue: https://github.com/terraform-google-modules/terraform-google-lb-http/issues/201

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
variables.tf
--- old/variables.tf
+++ new/variables.tf
@@ -81,9 +81,9 @@
 variable "backends" {
   description = "Map backend indices to list of backend maps."
   type = map(object({
-    port      = number
-    protocol  = string
-    port_name = string
+    port                    = number
+    protocol                = string
+    port_name               = string
     description             = string
     enable_cdn              = bool
     compression_mode        = string
Error: terraform fmt failed with exit code 3
Check the output for diffs and correct using terraform fmt <dir>
modules/serverless_negs/variables.tf
--- old/modules/serverless_negs/variables.tf
+++ new/modules/serverless_negs/variables.tf
@@ -58,8 +58,8 @@
 variable "backends" {
   description = "Map backend indices to list of backend maps."
   type = map(object({
-    protocol  = string
-    port_name = string
+    protocol                = string
+    port_name               = string
     description             = string
     enable_cdn              = bool
     compression_mode        = string
Error: terraform fmt failed with exit code 3
Check the output for diffs and correct using terraform fmt <dir>
modules/dynamic_backends/variables.tf
--- old/modules/dynamic_backends/variables.tf
+++ new/modules/dynamic_backends/variables.tf
@@ -81,9 +81,9 @@
 variable "backends" {
   description = "Map backend indices to list of backend maps."
   type = map(object({
-    port      = number
-    protocol  = string
-    port_name = string
+    port                    = number
+    protocol                = string
+    port_name               = string
     description             = string
     enable_cdn              = bool
     compression_mode        = string
Error: terraform fmt failed with exit code 3
Check the output for diffs and correct using terraform fmt <dir>
 ```

**Comment by gangsta** [comment]
maybe @bharathkkb can give some feedback here ?

**Comment by voycey** [comment]
So it seems @morgante has left Google - @bharathkkb can you please assign someone to look at tis ASAP - this is becoming painful now dealing with this

**Comment by gangsta** [comment]
I'll ping everyone in the org to get some attention.

@terraform-google-modules/cft-admins
@erjohnso
@tpdownes
@averbuks
@xingao267
@zefdelgadillo

**Review by bharathkkb — APPROVED** [review]
Thanks @gangsta and sorry for the delay!

**Comment by voycey** [comment]
Thanks @bharathkkb 🙏

**Comment by gangsta** [comment]
Thanks everyone :pray:

**Pull request merged**
