### PR TITLE
chore: add missing required var 'compression_mode' to the serverless_negs readme

### PR DESCRIPTION
**Pull request by prgres**
During implementing `serverless_neg` module, it came out that an one variable is missing from README example. I have added it

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@prgres
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_generate_modules
 The modules need to be regenerated. Please run `make_build`. 
 ```bash 
Checking submodule's files generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/serverless_negs/README.md /tmp/tmp.CqEj29KxA3/workspace/modules/serverless_negs/README.md
38c38
<       compression_mode                = null
---
> 
Error: submodule's files generation has not been run, please run the
'make build' command and commit changes
 ```

**Comment by comment-bot-dev** [comment]
@prgres
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_generate_modules
 The modules need to be regenerated. Please run `make_build`. 
 ```bash 
Checking submodule's files generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/modules/serverless_negs/README.md /tmp/tmp.iMbQh3Fnck/workspace/modules/serverless_negs/README.md
38c38
<       compression_mode                = null
---
> 
Error: submodule's files generation has not been run, please run the
'make build' command and commit changes
 ```

**Comment by comment-bot-dev** [comment]
@prgres
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@prgres
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by imrannayer** [comment]
@apeabody LGTM. Plz merge

**Review by apeabody — APPROVED** [review]
Thanks for the contribution @prgres!

**Pull request merged**
