### PR TITLE
fix: Update migration guide required parameters

### PR DESCRIPTION
**Pull request by dbburgess**
I encountered this error following the upgrade guide:

```
│ The given value is not suitable for child module variable "backends"
│ defined at
│ .terraform/modules/environment.lb_https/modules/serverless_negs/variables.tf:58,1-20:
│ element "server": attribute "port_name" is required.
```

I changed `port` to `port_name`, and it worked fine.

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@dbburgess
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by imrannayer** [comment]
LGTM
@apeabody can you plz merge?

**Review by apeabody — APPROVED** [review]

**Comment by apeabody** [comment]
Thanks for the contribution @dbburgess!

@imrannayer merged :)

**Pull request merged**
