### PR TITLE
Add support for session affinity on HTTP(S) LB

### PR DESCRIPTION
**Pull request by diasjorge**
This PR adds support for session affinity on http load balancers which I required for my application

### CODE REVIEW

**Comment by diasjorge** [comment]
I can't see why the build failed. I don't have permissions to see the build details.
For the examples, which ones should I update? Do I need to change the example to actually use session affinity? 
Thanks

**Comment by Dev25** [comment]
@diasjorge You need to update all examples to include the 2 new vars, you can just set them to `null`

You can run the CI tests locally via `make lint` or `make docker_test_integration`, i suggest just running `make lint` because the latter requires GCP access to spin up a project/loadbalancers etc

**Comment by diasjorge** [comment]
I pushed the request changes.

I ran `make docker_test_lint` and it was successful. The failing build I don't have any feedback why it breaks. Could you tell me what's the issue?

**Comment by diasjorge** [comment]
any possibility to move forward with this PR?

**Pull request merged**
