### PR TITLE
fix: add backend.groups.description variable to serverless_neg

### PR DESCRIPTION
**Pull request by Sonins**
It seems description variable is being used in module like below.

```terraform
# modules/serverless_neg
resource "google_compute_backend_service" "default" {
...
  dynamic "backend" {
    for_each = toset(each.value["groups"])
    content {
      description = lookup(backend.value, "description", null)
      group       = backend.value["group"]

    }
  }
...
}
```

But there's no description in variables.tf, and documentation.

### CODE REVIEW

**Comment by imrannayer** [comment]
@Sonins plz update [template here](https://github.com/terraform-google-modules/terraform-google-lb-http/blob/804b7b9f9cedf234a2973e13c5ab78c8fec6ee12/autogen/variables.tf.tmpl#L141) and follow [this doc](https://github.com/terraform-google-modules/terraform-google-lb-http/blob/master/CONTRIBUTING.md) to generate the code and submit.

**Comment by Sonins** [comment]
@imrannayer Just fixed it, can you check?

**Review by imrannayer — APPROVED** [review]

**Pull request merged**
