### PR TITLE
feat: Add project for backend service and health check for cross project reference

### PR DESCRIPTION
**Pull request by cgsyam**
In External Application Load Balancers, the cross project backend reference is now GA for most of the backend types except GCS. https://cloud.google.com/load-balancing/docs/https#cross-project. 

Adding capability to module for creating cross project backends.

### CODE REVIEW

**Comment by cgsyam** [comment]
@imrannayer Sure. Will add a test. Also I updated PR with using `coalesce` rather than `lookup` for project (changed based on the last /gcbrun results). Can you please run another `/gcgrun` when able?

**Comment by imrannayer** [comment]
@cgsyam can you plz create test using [new framework](https://codelabs.developers.google.com/cft-onboarding/#6)?
Check [cloud armor module](https://github.com/GoogleCloudPlatform/terraform-google-cloud-armor/tree/main/test/integration/simple-example) as an example

**Comment by syam-zee** [comment]
@imrannayer Added tests. New framework approach seems significantly different from what we have on this repo. I can check on that, but can we take it as a separate issue for moving to new approach? Happy to contribute.

**Comment by cgsyam** [comment]
@imrannayer Added tests. New framework approach seems significantly different from what we have on this repo. I can check on that, but can we take it as a separate issue for moving to new approach? Happy to contribute.

**Comment by cgsyam** [comment]
@imrannayer The tests were running successfully on local (with the the repo local test orchestration). But `/gcbrun` failing to get the get the data for `google_project` on service project, ie second project. I now added an explicit provider on data block to verify. Can you please run `/gcbrun` when able.

**Pull request merged**
