### PR TITLE
feat: Added network for internal_managed load balancing scheme

### PR DESCRIPTION
**Pull request by vedit**
Completes the implementation started with #257  with necessary network input for non-default networks and making the public_ip creation dependent on the loadbalancing scheme

### CODE REVIEW

**Comment by vedit** [comment]
I signed CLA, don't know how to re-trigger that particular check

**Comment by comment-bot-dev** [comment]
@vedit
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_generate_modules
 The modules need to be regenerated. Please run `make_build`. 
 ```bash 
Checking submodule's files generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/main.tf /tmp/tmp.TWgWZVUJZI/workspace/main.tf
19d18
<   is_internal  = var.load_balancing_scheme == "INTERNAL_SELF_MANAGED"
25d23
<   internal_network    = local.is_internal ? var.network : null
42d39
<   network               = local.internal_network
55d51
<   network               = local.internal_network
60c56
<   count      = local.is_internal ? 0 : var.create_address ? 1 : 0
---
>   count      = var.create_address ? 1 : 0
79d74
<   network               = local.internal_network
92d86
<   network               = local.internal_network
97c91
<   count      = local.is_internal ? 0 : (var.enable_ipv6 && var.create_ipv6_address) ? 1 : 0
---
>   count      = (var.enable_ipv6 && var.create_ipv6_address) ? 1 : 0
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/outputs.tf /tmp/tmp.TWgWZVUJZI/workspace/outputs.tf
23,24c23,24
< output "ip_address" {
<   description = "The IPv4 assigned to the global fowarding rule."
---
> output "external_ip" {
>   description = "The external IPv4 assigned to the global fowarding rule."
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' /workspace/variables.tf /tmp/tmp.TWgWZVUJZI/workspace/variables.tf
63,68d62
< variable "network" {
<   description = "Network for INTERNAL_SELF_MANAGED load balancing scheme"
<   type        = string
<   default     = "default"
< }
< 
Error: submodule's files generation has not been run, please run the
'make build' command and commit changes
 ``` 
- ⚠️check_documentation
 The documentation needs to be regenerated. Please run `make generate_docs`. 
 ```bash 
Checking for documentation generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=autogen' '--exclude=*.tfvars' '--exclude=*metadata.yaml' /workspace/README.md /tmp/tmp.bGrTc9qoWA/generate_docs/workspace/README.md
132a133
> | network | Network for INTERNAL\_SELF\_MANAGED load balancing scheme | `string` | `"default"` | no |
151d151
< | external\_ip | The external IPv4 assigned to the global fowarding rule. |
154a155
> | ip\_address | The IPv4 assigned to the global fowarding rule. |
Error: Documentation generation has not been run, please run the
'make docker_generate_docs' command and commit the above changes.
 ``` 
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
Running terraform validate
terraform_validate .
Success!
 The configuration is valid.
terraform_validate ./examples/cloudrun
Success!
 The configuration is valid.
terraform_validate ./examples/dynamic-backend
Success!
 The configuration is valid.
terraform_validate ./examples/https-gke
╷
│
 
Error: 
Unsupported attribute
│
 
│
 
  on outputs.tf line 18, in output "load-balancer-ip":
│
 
  18:   value = module.gce-lb-https
.external_ip
│
 
    
├────────────────
│
 
    
│
 
module.gce-lb-https
 is a object
│
 
│
 
This object does not have an attribute named "external_ip".
╵
terraform_validate ./examples/https-gke/gke-node-port
Success!
 The configuration is valid.
terraform_validate ./examples/https-redirect
Success!
 The configuration is valid.
terraform_validate ./examples/mig-nat-http-lb
╷
│
 
Error: 
Unsupported attribute
│
 
│
 
  on outputs.tf line 18, in output "load-balancer-ip":
│
 
  18:   value = module.gce-lb-http
.external_ip
│
 
    
├────────────────
│
 
    
│
 
module.gce-lb-http
 is a object
│
 
│
 
This object does not have an attribute named "external_ip".
╵
terraform_validate ./examples/multi-backend-multi-mig-bucket-https-lb
Success!
 The configuration is valid.
terraform_validate ./examples/multi-mig-http-lb
Success!
 The configuration is valid.
terraform_validate ./examples/multiple-certs
╷
│
 
Error: 
Unsupported attribute
│
 
│
 
  on outputs.tf line 30, in output "load-balancer-ip":
│
 
  30:   value = module.gce-lb-https
.external_ip
│
 
    
├────────────────
│
 
    
│
 
module.gce-lb-https
 is a object
│
 
│
 
This object does not have an attribute named "external_ip".
╵
╷
│
 
Error: 
Unsupported attribute
│
 
│
 
  on outputs.tf line 39, in output "asset-url":
│
 
  39:   value = "https://${module.gce-lb-https
.external_ip
}/assets/gcp-logo.svg"
│
 
    
├────────────────
│
 
    
│
 
module.gce-lb-https
 is a object
│
 
│
 
This object does not have an attribute named "external_ip".
╵
terraform_validate ./examples/shared-vpc
Success!
 The configuration is valid.
terraform_validate ./modules/dynamic_backends
Success!
 The configuration is valid.
terraform_validate ./modules/serverless_negs
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/cloudrun
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/https-redirect
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/mig_nat
╷
│
 
Error: 
Unsupported attribute
│
 
│
 
  on ../../../examples/mig-nat-http-lb/outputs.tf line 18, in output "load-balancer-ip":
│
 
  18:   value = module.gce-lb-http
.external_ip
│
 
    
├────────────────
│
 
    
│
 
module.gce-lb-http
 is a object
│
 
│
 
This object does not have an attribute named "external_ip".
╵
terraform_validate ./test/fixtures/multi_certs
╷
│
 
Error: 
Unsupported attribute
│
 
│
 
  on ../../../examples/multiple-certs/outputs.tf line 30, in output "load-balancer-ip":
│
 
  30:   value = module.gce-lb-https
.external_ip
│
 
    
├────────────────
│
 
    
│
 
module.gce-lb-https
 is a object
│
 
│
 
This object does not have an attribute named "external_ip".
╵
╷
│
 
Error: 
Unsupported attribute
│
 
│
 
  on ../../../examples/multiple-certs/outputs.tf line 39, in output "asset-url":
│
 
  39:   value = "https://${module.gce-lb-https
.external_ip
}/assets/gcp-logo.svg"
│
 
    
├────────────────
│
 
    
│
 
module.gce-lb-https
 is a object
│
 
│
 
This object does not have an attribute named "external_ip".
╵
terraform_validate ./test/fixtures/multi_mig
Success!
 The configuration is valid.
terraform_validate ./test/setup
Success!
 The configuration is valid.
 ```

**Comment by fabioformosa** [comment]
> Completes the implementation started with #257 with necessary network input for non-default networks and making the public_ip creation dependent on the loadbalancing scheme

Hi @vedit , any news about this PR.
I'm facing the same issue related to the fact that the network field is not set and it seems to be mandatory in case of INTERNAL_SELF_MANAGED load-balancer

**Comment by imrannayer** [comment]
@vedit r u still working on this PR?

**Comment by imrannayer** [comment]
Fixed in #320

**Pull request closed without merging**
