### PR TITLE
Allow choosing a protocol for Serverless NEGs

### PR DESCRIPTION
**Pull request by cagataygurturk**
It is possible to enable HTTP/2 between GLB and serverless network endpoints. This PR makes the necessary change that allows setting protocol, so HTTP/2 can be chosen for GLB <> Serverless NEG communication.

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
modules/serverless_negs/main.tf
--- old/modules/serverless_negs/main.tf
+++ new/modules/serverless_negs/main.tf
@@ -148,7 +148,7 @@
   project = var.project
   name    = "${var.name}-backend-${each.key}"
 
-  protocol                        = lookup(each.value, "protocol", "HTTP")
+  protocol = lookup(each.value, "protocol", "HTTP")
 
   description                     = lookup(each.value, "description", null)
   connection_draining_timeout_sec = lookup(each.value, "connection_draining_timeout_sec", null)
Error: terraform fmt failed with exit code 3
Check the output for diffs and correct using terraform fmt <dir>
modules/serverless_negs/variables.tf
--- old/modules/serverless_negs/variables.tf
+++ new/modules/serverless_negs/variables.tf
@@ -58,7 +58,7 @@
 variable "backends" {
   description = "Map backend indices to list of backend maps."
   type = map(object({
-    protocol  = string
+    protocol = string
 
     description            = string
     enable_cdn             = bool
Error: terraform fmt failed with exit code 3
Check the output for diffs and correct using terraform fmt <dir>
 ```

**Comment by paddie** [comment]
@cagataygurturk is this to enable `https` protocol or what is the purpose of this?

**Comment by cagataygurturk** [comment]
It is possible to enable HTTP/2 between GLB and serverless endpoints. This PR is trying to enable that option.

**Comment by morgante** [comment]
@cagataygurturk Would you mind fixing the formatting error?

**Comment by morgante** [comment]
@cagataygurturk Are you sure setting the protocol is actually required for serverless NEGs?

In [the documentation](https://cloud.google.com/load-balancing/docs/https/setting-up-https-serverless#console_1), it says the "protocol" parameter is ignored for serverless NEGs and some internal investigation seems to confirm that.

**Comment by cagataygurturk** [comment]
> @cagataygurturk Are you sure setting the protocol is actually required for serverless NEGs?
> 
> In [the documentation](https://cloud.google.com/load-balancing/docs/https/setting-up-https-serverless#console_1), it says the "protocol" parameter is ignored for serverless NEGs and some internal investigation seems to confirm that.

Can you point out exactly where in that document it is stated that protocol is ignored? Both the API and Console allows protocol selection with NEGs and I couldn't find any information about protocol being ignored, hence I sent this PR.

**Comment by morgante** [comment]
image

**Comment by cagataygurturk** [comment]
Then this PR goes to trash :) Thanks!

**Comment by morgante** [comment]
@cagataygurturk Thanks for contributing though and sorry for not catching this earlier.

**Pull request closed without merging**
